# Load balancer for the Node pods
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-lb
  name: node-lb
spec:
  type: LoadBalancer
  selector:
    app: node-pod
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
      protocol: TCP
