# Deployment for the Node pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-delp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-pod
  template:
    metadata:
      labels:
        app: node-pod
    spec:
      containers:
        - name: node-pod
          image: aminerachyd/projetandroid-server:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
---
# Service for the Node pods
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-pod
  ports:
    - port: 5000
      targetPort: 5000
