name: Test du serveur

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  server_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test du serveur
        working-directory: ./server
        run: |
          npm install
          npm install -D mocha
          npm run test

  image_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: aminerachyd/projetandroid-server

  # image_deployment:
  #   runs-on: ubuntu-20.04

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Test du serveur
  #       run: |
  #         cd server
  #         npm install
  #         npm install -D mocha
  #         npm run test
